#!/usr/bin/env python3
"""
Sync legal copyright information across all repositories in configured organizations.

Reads the copyright holder from this template's LICENSE and propagates it to:
  - LICENSE          : Copyright holder line (preserves year and license type)
  - mkdocs.yml       : copyright field (preserves HTML structure and URL)
  - CITATION.cff     : affiliation field(s) (preserves author names)
  - README.md        : any Copyright lines (preserves year)

Opt-out: add .github/.templatesync-ignore to a repo with filenames to skip,
or a single '*' to skip the repo entirely.
"""

import base64
import os
import re
import sys
import requests

API = "https://api.github.com"
TOKEN = os.environ["SYNC_PAT"]
COPYRIGHT_HOLDER = os.environ["COPYRIGHT_HOLDER"]
ORGS = [o.strip() for o in os.environ.get("ORGS", "THD-Spatial-AI,enerplanet").split(",")]
DRY_RUN = os.environ.get("DRY_RUN", "false").lower() == "true"
TEMPLATE_REPO = os.environ.get("TEMPLATE_REPO", "")

SYNC_BRANCH = "template-sync/legal-update"
IGNORE_FILE = ".github/.templatesync-ignore"

HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


# ---------------------------------------------------------------------------
# GitHub API helpers
# ---------------------------------------------------------------------------

def gh_get(path, params=None):
    resp = requests.get(f"{API}{path}", headers=HEADERS, params=params)
    resp.raise_for_status()
    return resp.json()


def gh_post(path, data):
    resp = requests.post(f"{API}{path}", headers=HEADERS, json=data)
    resp.raise_for_status()
    return resp.json()


def gh_put(path, data):
    resp = requests.put(f"{API}{path}", headers=HEADERS, json=data)
    resp.raise_for_status()
    return resp.json()


def gh_patch(path, data):
    resp = requests.patch(f"{API}{path}", headers=HEADERS, json=data)
    resp.raise_for_status()
    return resp.json()


def get_file(repo, path, ref="HEAD"):
    try:
        data = gh_get(f"/repos/{repo}/contents/{path}", params={"ref": ref})
        return base64.b64decode(data["content"]).decode("utf-8"), data["sha"]
    except requests.HTTPError as e:
        if e.response.status_code in (404, 403):
            return None, None
        raise


def put_file(repo, path, content, sha, branch, message):
    gh_put(f"/repos/{repo}/contents/{path}", {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "sha": sha,
        "branch": branch,
    })


def default_branch(repo):
    return gh_get(f"/repos/{repo}")["default_branch"]


def branch_sha(repo, branch):
    return gh_get(f"/repos/{repo}/git/ref/heads/{branch}")["object"]["sha"]


def create_branch(repo, name, sha):
    try:
        gh_post(f"/repos/{repo}/git/refs", {"ref": f"refs/heads/{name}", "sha": sha})
    except requests.HTTPError as e:
        if e.response.status_code == 422:
            # Branch exists — reset to current base so file SHAs are fresh
            gh_patch(f"/repos/{repo}/git/refs/heads/{name}", {"sha": sha, "force": True})
        else:
            raise


def open_pr(repo, head, base):
    existing = gh_get(f"/repos/{repo}/pulls", params={
        "head": f"{repo.split('/')[0]}:{head}", "state": "open"
    })
    if existing:
        print(f"    PR already open: {existing[0]['html_url']}")
        return
    pr = gh_post(f"/repos/{repo}/pulls", {
        "title": "[Template Sync] Update legal copyright information",
        "body": PR_BODY,
        "head": head,
        "base": base,
    })
    print(f"    PR created: {pr['html_url']}")


def list_repos(org):
    repos, page = [], 1
    while True:
        batch = gh_get(f"/orgs/{org}/repos", params={"per_page": 100, "page": page, "type": "all"})
        if not batch:
            break
        repos.extend(batch)
        page += 1
    return repos


PR_BODY = f"""\
## Template Sync: Legal Copyright Update

This PR updates the copyright holder to match the central template.

**New copyright holder:** `{COPYRIGHT_HOLDER}`

**Files updated (where present and changed):**
- `LICENSE` — copyright holder line (license type and year preserved)
- `mkdocs.yml` — `copyright:` field
- `CITATION.cff` — `affiliation:` field(s)
- `README.md` — any copyright lines

---
To opt out of future syncs for specific files, create `.github/.templatesync-ignore` \
with one filename per line. Use `*` to skip this repo entirely.

*Auto-generated by [GitHub Template Sync](https://github.com/{TEMPLATE_REPO})*
"""


# ---------------------------------------------------------------------------
# Per-file update logic
# ---------------------------------------------------------------------------

def update_license(content, holder):
    """Replace copyright holder; preserve year and license type."""
    new = re.sub(
        r'(Copyright\s+(?:\(c\)|\(C\)|©)\s+\d{4}(?:-\d{4})?\s+).+',
        rf'\g<1>{holder}',
        content,
    )
    return new, new != content


def update_mkdocs(content, holder):
    """Replace link text inside the mkdocs copyright field."""
    # Handles: copyright: | \n  &copy; YEAR <a ...>NAME</a>
    new = re.sub(
        r'(copyright:.*?<a[^>]*>)([^<]+)(</a>)',
        rf'\g<1>{holder}\g<3>',
        content,
        flags=re.DOTALL,
    )
    if new != content:
        return new, True
    # Fallback: plain-text copyright line (no HTML)
    new = re.sub(
        r'(copyright:\s*["\']?(?:&copy;|©)\s*\d{4}(?:-\d{4})?\s+)([^"\'\n]+)',
        rf'\g<1>{holder}',
        content,
    )
    return new, new != content


def update_citation(content, holder):
    """Replace all affiliation values."""
    new = re.sub(r'(affiliation:\s*")([^"]+)(")', rf'\g<1>{holder}\g<3>', content)
    return new, new != content


def update_readme(content, holder):
    """Replace copyright holder in any Copyright lines."""
    new = re.sub(
        r'(Copyright\s+(?:\(c\)|\(C\)|©)\s+\d{4}(?:-\d{4})?\s+).+',
        rf'\g<1>{holder}',
        content,
    )
    return new, new != content


UPDATERS = {
    "LICENSE":       update_license,
    "mkdocs.yml":    update_mkdocs,
    "CITATION.cff":  update_citation,
    "README.md":     update_readme,
}


# ---------------------------------------------------------------------------
# Per-repo processing
# ---------------------------------------------------------------------------

def process_repo(repo):
    full = repo["full_name"]
    print(f"\n  {full}")

    if repo.get("archived"):
        print("    skip: archived")
        return
    if repo.get("fork"):
        print("    skip: fork")
        return
    if full == TEMPLATE_REPO:
        print("    skip: template repo")
        return

    ignore_content, _ = get_file(full, IGNORE_FILE)
    ignored = set()
    if ignore_content:
        ignored = {l.strip() for l in ignore_content.splitlines() if l.strip() and not l.startswith("#")}
    if "*" in ignored:
        print("    skip: opted out entirely")
        return

    base = default_branch(full)
    base_sha = branch_sha(full, base)

    pending = {}  # filename -> (new_content, blob_sha)
    for filename, updater in UPDATERS.items():
        if filename in ignored:
            print(f"    skip {filename}: ignored")
            continue
        content, sha = get_file(full, filename)
        if content is None:
            continue
        new_content, changed = updater(content, COPYRIGHT_HOLDER)
        if changed:
            pending[filename] = (new_content, sha)
            print(f"    will update: {filename}")
        else:
            print(f"    up-to-date:  {filename}")

    if not pending:
        print("    nothing to do")
        return

    if DRY_RUN:
        print(f"    [dry-run] would update: {', '.join(pending)}")
        return

    create_branch(full, SYNC_BRANCH, base_sha)
    for filename, (new_content, sha) in pending.items():
        put_file(full, filename, new_content, sha, SYNC_BRANCH,
                 f"chore: sync copyright holder in {filename}")
    open_pr(full, SYNC_BRANCH, base)


def main():
    print(f"Copyright holder : {COPYRIGHT_HOLDER}")
    print(f"Organizations    : {', '.join(ORGS)}")
    print(f"Dry run          : {DRY_RUN}")

    errors = []
    for org in ORGS:
        print(f"\n=== {org} ===")
        repos = list_repos(org)
        print(f"  {len(repos)} repositories")
        for repo in repos:
            try:
                process_repo(repo)
            except Exception as exc:
                msg = f"  ERROR {repo['full_name']}: {exc}"
                print(msg)
                errors.append(msg)

    if errors:
        print("\nFailed repos:")
        for e in errors:
            print(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
