image: docker

variables:
  SHORT_IMAGE_NAME: s6et_webservice
  FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE/$SHORT_IMAGE_NAME:latest

stages:
  - build
  - push

build_images:
  stage: build
  tags:
    - tcf-webservice
  before_script:
    - mv .env.docker .env
    - sed -i "1s/^/DOMAIN=192.168.80.21\n/" .env
    - cat .env
  script:
    - make
  only:
    - integrated-Webservice

push_images:
  stage: push
  tags:
    - tcf-webservice
  before_script:
    - docker tag $SHORT_IMAGE_NAME:latest $FULL_IMAGE_NAME 
    - docker login -u $DEPLOY_TOKEN_NAME -p $DEPLOY_TOKEN_PASSWORD $CI_REGISTRY
    - echo "Login success"
  script:
    - docker-compose -f docker-compose.unltd.yaml push $FULL_IMAGE_NAME
  only:
    - integrated-Webservice
