services:
    pv_simulation_EnerplanET:
        image: pv-nrel-pysam:latest
        volumes:
            - sim_shared_data:/webservice/data
            - sim_shared_data:/pv_simulation/output_data
        platform: linux/amd64
        build:
            context: .
            dockerfile: renewables/pv.dockerfile
        restart: always
        ports:
            - 8092:8082/tcp
        environment:
            - GUNICORN_WORKERS=${PV_WORKERS:-15}
            - GUNICORN_TIMEOUT=0
        networks:
            sim_network:
                ipv4_address: 172.20.0.3

volumes:
  sim_shared_data:
    external: true

networks:
    sim_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1